# Industrial Quality Control Computer Vision System Configuration

# Model Configuration
model:
  # YOLO Detection Model
  yolo_weights: "models/yolov8_qc.pt"
  confidence_threshold: 0.7
  nms_threshold: 0.5
  
  # ResNet Classification Model
  resnet_weights: "models/resnet50_qc.pt"
  num_classes: 5
  
  # Ensemble Settings
  ensemble_weights:
    yolo: 0.6
    resnet: 0.4

# Processing Configuration
processing:
  batch_size: 8
  max_workers: 4
  enable_gpu: true
  tensorrt_optimization: true
  input_size: [640, 640]
  
  # Image Preprocessing
  preprocessing:
    resize: [640, 640]
    normalize: true
    denoise: false
    enhance_contrast: false

# Quality Control Settings
quality_control:
  defect_classes:
    - "crack"
    - "scratch"
    - "dent"
    - "discoloration"
    - "contamination"
  
  severity_levels:
    - "minor"
    - "major"
    - "critical"
  
  # Quality Thresholds
  thresholds:
    minor_defect_limit: 3
    major_defect_limit: 1
    critical_defect_limit: 0
    confidence_threshold: 0.8
    area_threshold_percent: 5.0

# Statistical Process Control
spc:
  window_size: 100
  confidence_level: 0.95
  control_chart_types:
    - "c-chart"    # Count chart
    - "u-chart"    # Rate chart
    - "x-chart"    # Individual values
  
  # Control Limits
  specification_limits:
    defect_rate:
      upper: 5.0
      lower: 0.0
      target: 0.5
    confidence_score:
      lower: 0.8
      target: 0.95

# Alert Configuration
alerts:
  email_notifications: true
  sms_notifications: false
  webhook_notifications: true
  
  # Alert Thresholds
  thresholds:
    critical_defects: 1
    major_defects: 2
    high_defect_rate: 3.0
    low_confidence: 0.6
  
  # Notification Settings
  email:
    smtp_server: "smtp.company.com"
    smtp_port: 587
    username: "qc-system@company.com"
    recipients:
      - "quality.manager@company.com"
      - "production.supervisor@company.com"
  
  webhook_url: "https://your-webhook.com/alerts"

# Data Storage
storage:
  # Database Configuration
  database:
    type: "sqlite"  # sqlite, mysql, postgresql
    host: "localhost"
    port: 5432
    name: "qc_database"
    username: "qc_user"
    password: "secure_password"
  
  # Image Storage
  image_storage:
    save_processed_images: true
    save_failed_images: true
    storage_path: "data/images"
    max_storage_gb: 100
    retention_days: 30
  
  # Results Storage
  results_storage:
    save_detailed_results: true
    export_format: "json"
    backup_frequency: "daily"

# Performance Monitoring
monitoring:
  enable_metrics: true
  metrics_port: 9090
  log_level: "INFO"
  
  # Performance Targets
  targets:
    inference_time_ms: 150
    throughput_images_per_minute: 500
    accuracy_percent: 94.0
    precision_percent: 91.0
    recall_percent: 89.0

# Edge Computing
edge:
  enable_tensorrt: true
  precision: "fp16"  # fp32, fp16, int8
  max_batch_size: 8
  workspace_size_gb: 2
  
  # Optimization Settings
  optimization:
    enable_dynamic_shapes: false
    enable_fp16: true
    enable_int8: false
    calibration_dataset: "data/calibration"

# API Configuration
api:
  host: "0.0.0.0"
  port: 5000
  debug: false
  cors_enabled: true
  rate_limiting:
    enabled: true
    requests_per_minute: 1000
  
  # Authentication
  authentication:
    enabled: false
    jwt_secret: "your-jwt-secret"
    token_expiry_hours: 24

# Dashboard Configuration
dashboard:
  refresh_interval_seconds: 5
  max_display_results: 100
  enable_real_time: true
  
  # Chart Settings
  charts:
    spc_chart_points: 50
    trend_analysis_days: 7
    histogram_bins: 20

# Logging Configuration
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file_path: "logs/qc_system.log"
  max_file_size_mb: 100
  backup_count: 5
  
  # Component Logging
  loggers:
    models: "INFO"
    inference: "INFO"
    analytics: "INFO"
    api: "INFO"
    spc: "DEBUG"

# Training Configuration (for model retraining)
training:
  # Data Augmentation
  augmentation:
    enabled: true
    rotation_range: 15
    brightness_range: 0.2
    contrast_range: 0.2
    noise_factor: 0.1
  
  # Training Parameters
  parameters:
    epochs: 100
    batch_size: 16
    learning_rate: 0.001
    validation_split: 0.2
    early_stopping_patience: 10
  
  # Model Checkpointing
  checkpointing:
    save_best_only: true
    monitor: "val_accuracy"
    save_frequency: 10

# Production Environment
production:
  # Scaling
  scaling:
    auto_scale: false
    min_instances: 1
    max_instances: 4
    cpu_threshold: 80
    memory_threshold: 85
  
  # Health Checks
  health_checks:
    enabled: true
    interval_seconds: 30
    timeout_seconds: 10
    failure_threshold: 3
  
  # Backup and Recovery
  backup:
    enabled: true
    frequency: "daily"
    retention_days: 30
    backup_path: "backups/"

# Integration Settings
integrations:
  # Manufacturing Execution System
  mes:
    enabled: false
    endpoint: "http://mes-system.company.com/api"
    api_key: "your-mes-api-key"
  
  # Enterprise Resource Planning
  erp:
    enabled: false
    endpoint: "http://erp-system.company.com/api"
    username: "qc_integration"
    password: "secure_password"
  
  # Quality Management System
  qms:
    enabled: false
    endpoint: "http://qms.company.com/api"
    integration_type: "real_time"

# Security Configuration
security:
  # SSL/TLS
  ssl:
    enabled: false
    cert_file: "certs/server.crt"
    key_file: "certs/server.key"
  
  # API Security
  api_security:
    rate_limiting: true
    input_validation: true
    output_sanitization: true
  
  # Data Encryption
  encryption:
    encrypt_stored_images: false
    encrypt_results: false
    encryption_key: "your-encryption-key"

# Development and Testing
development:
  # Debug Settings
  debug:
    save_intermediate_results: false
    enable_model_profiling: false
    detailed_error_messages: true
  
  # Testing
  testing:
    test_data_path: "tests/data"
    benchmark_iterations: 10
    performance_baseline_ms: 150
