# ResNet-50 Training Configuration for Quality Control Classification

# Model Configuration
model:
  architecture: "resnet50"
  pretrained: true
  num_classes: 5
  input_size: [224, 224]
  dropout_rate: 0.5

# Training Parameters
training:
  epochs: 100
  batch_size: 32
  learning_rate: 0.001
  weight_decay: 1e-4
  momentum: 0.9
  
  # Learning rate scheduling
  lr_scheduler:
    type: "StepLR"  # StepLR, CosineAnnealingLR, ReduceLROnPlateau
    step_size: 30
    gamma: 0.1
    patience: 10  # For ReduceLROnPlateau
  
  # Early stopping
  early_stopping:
    enabled: true
    patience: 15
    min_delta: 0.001
    monitor: "val_accuracy"
  
  # Optimizer settings
  optimizer: "Adam"  # Adam, SGD, AdamW
  
  # Loss function
  loss_function: "CrossEntropyLoss"
  label_smoothing: 0.1
  
  # Mixed precision training
  mixed_precision: true

# Dataset Configuration
data:
  # Dataset paths
  dataset_root: "datasets/qc_classification"
  train_path: "datasets/qc_classification/train"
  val_path: "datasets/qc_classification/val"
  test_path: "datasets/qc_classification/test"
  
  # Class definitions
  classes:
    0: "crack"
    1: "scratch"
    2: "dent"
    3: "discoloration"
    4: "contamination"
  
  # Dataset splits
  train_split: 0.7
  val_split: 0.2
  test_split: 0.1
  
  # Class balance
  balance_dataset: true
  oversample_minority: true
  undersample_majority: false

# Data Preprocessing
preprocessing:
  # Normalization (ImageNet stats)
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  
  # Resize settings
  resize:
    size: [224, 224]
    interpolation: "bilinear"
  
  # Center crop
  center_crop: 224

# Data Augmentation
augmentation:
  # Training augmentations
  train:
    random_resize_crop:
      size: 224
      scale: [0.8, 1.0]
      ratio: [0.75, 1.33]
    
    random_horizontal_flip:
      probability: 0.5
    
    random_vertical_flip:
      probability: 0.1
    
    random_rotation:
      degrees: 15
    
    color_jitter:
      brightness: 0.2
      contrast: 0.2
      saturation: 0.2
      hue: 0.1
    
    random_grayscale:
      probability: 0.1
    
    # Advanced augmentations
    random_erasing:
      enabled: true
      probability: 0.25
      scale: [0.02, 0.33]
      ratio: [0.3, 3.3]
    
    gaussian_blur:
      enabled: true
      probability: 0.1
      kernel_size: 3
    
    # Cutout/CutMix
    cutout:
      enabled: false
      probability: 0.25
      max_holes: 1
      max_height: 16
      max_width: 16
    
    cutmix:
      enabled: false
      alpha: 1.0
      probability: 0.5
    
    mixup:
      enabled: false
      alpha: 0.2
      probability: 0.5
  
  # Validation augmentations (minimal)
  val:
    resize: 256
    center_crop: 224

# Model Architecture Modifications
architecture:
  # Feature extraction
  freeze_backbone: false
  freeze_layers: 0  # Number of layers to freeze from start
  
  # Custom classifier head
  classifier:
    hidden_layers: [512]
    activation: "ReLU"
    batch_norm: true
    dropout: [0.3, 0.5]
  
  # Attention mechanisms
  attention:
    enabled: false
    type: "SE"  # SE (Squeeze-Excite), CBAM, etc.

# Transfer Learning
transfer_learning:
  # Pretrained model source
  pretrained_source: "imagenet"
  
  # Fine-tuning strategy
  strategy: "gradual_unfreezing"
  
  # Unfreezing schedule
  unfreeze_schedule:
    - epoch: 10
      layers: ["layer4"]
    - epoch: 20
      layers: ["layer3", "layer4"]
    - epoch:
